// Code generated by "stringer -type=Opcode"; DO NOT EDIT.

package isa

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpcodeMask-63]
	_ = x[Add-0]
	_ = x[Arg-1]
	_ = x[ArgsLen-2]
	_ = x[ArgsPop-3]
	_ = x[ArgsPush-4]
	_ = x[Call-5]
	_ = x[Call0-6]
	_ = x[Call1-7]
	_ = x[Call2-8]
	_ = x[Call3-9]
	_ = x[CallSelf-10]
	_ = x[CallWith-11]
	_ = x[Car-12]
	_ = x[Cdr-13]
	_ = x[Closure-14]
	_ = x[CondJump-15]
	_ = x[Cons-16]
	_ = x[Const-17]
	_ = x[Div-18]
	_ = x[Dup-19]
	_ = x[Empty-20]
	_ = x[Eq-21]
	_ = x[False-22]
	_ = x[EnvBind-23]
	_ = x[EnvPrivate-24]
	_ = x[EnvPublic-25]
	_ = x[EnvValue-26]
	_ = x[Jump-27]
	_ = x[Label-28]
	_ = x[Load-29]
	_ = x[Mod-30]
	_ = x[Mul-31]
	_ = x[Neg-32]
	_ = x[NegInt-33]
	_ = x[NewRef-34]
	_ = x[NoOp-35]
	_ = x[Not-36]
	_ = x[Null-37]
	_ = x[NumEq-38]
	_ = x[NumGt-39]
	_ = x[NumGte-40]
	_ = x[NumLt-41]
	_ = x[NumLte-42]
	_ = x[Panic-43]
	_ = x[Pop-44]
	_ = x[PosInt-45]
	_ = x[RefBind-46]
	_ = x[RefValue-47]
	_ = x[RestArg-48]
	_ = x[RetFalse-49]
	_ = x[RetNull-50]
	_ = x[RetTrue-51]
	_ = x[Return-52]
	_ = x[Store-53]
	_ = x[Sub-54]
	_ = x[TailCall-55]
	_ = x[TailClos-56]
	_ = x[TailSelf-57]
	_ = x[True-58]
	_ = x[Vector-59]
	_ = x[Zero-60]
}

const (
	_Opcode_name_0 = "AddArgArgsLenArgsPopArgsPushCallCall0Call1Call2Call3CallSelfCallWithCarCdrClosureCondJumpConsConstDivDupEmptyEqFalseEnvBindEnvPrivateEnvPublicEnvValueJumpLabelLoadModMulNegNegIntNewRefNoOpNotNullNumEqNumGtNumGteNumLtNumLtePanicPopPosIntRefBindRefValueRestArgRetFalseRetNullRetTrueReturnStoreSubTailCallTailClosTailSelfTrueVectorZero"
	_Opcode_name_1 = "OpcodeMask"
)

var (
	_Opcode_index_0 = [...]uint16{0, 3, 6, 13, 20, 28, 32, 37, 42, 47, 52, 60, 68, 71, 74, 81, 89, 93, 98, 101, 104, 109, 111, 116, 123, 133, 142, 150, 154, 159, 163, 166, 169, 172, 178, 184, 188, 191, 195, 200, 205, 211, 216, 222, 227, 230, 236, 243, 251, 258, 266, 273, 280, 286, 291, 294, 302, 310, 318, 322, 328, 332}
)

func (i Opcode) String() string {
	switch {
	case i <= 60:
		return _Opcode_name_0[_Opcode_index_0[i]:_Opcode_index_0[i+1]]
	case i == 63:
		return _Opcode_name_1
	default:
		return "Opcode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
