// Code generated by "stringer -type=Opcode"; DO NOT EDIT.

package isa

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpcodeMask-127]
	_ = x[Label-0]
	_ = x[NoOp-1]
	_ = x[Arg-2]
	_ = x[ArgsLen-3]
	_ = x[ArgsPop-4]
	_ = x[ArgsPush-5]
	_ = x[ArgsRest-6]
	_ = x[Closure-7]
	_ = x[EnvBind-8]
	_ = x[EnvPrivate-9]
	_ = x[EnvPublic-10]
	_ = x[EnvValue-11]
	_ = x[Load-12]
	_ = x[NewRef-13]
	_ = x[RefBind-14]
	_ = x[RefValue-15]
	_ = x[Store-16]
	_ = x[Dup-17]
	_ = x[Pop-18]
	_ = x[Const-19]
	_ = x[False-20]
	_ = x[Null-21]
	_ = x[True-22]
	_ = x[Zero-23]
	_ = x[Call-24]
	_ = x[Call0-25]
	_ = x[Call1-26]
	_ = x[Call2-27]
	_ = x[Call3-28]
	_ = x[CallSelf-29]
	_ = x[CallWith-30]
	_ = x[TailCall-31]
	_ = x[TailClos-32]
	_ = x[TailSelf-33]
	_ = x[CondJump-34]
	_ = x[Jump-35]
	_ = x[Panic-36]
	_ = x[RetFalse-37]
	_ = x[RetNull-38]
	_ = x[RetTrue-39]
	_ = x[Return-40]
	_ = x[Append-41]
	_ = x[Assoc-42]
	_ = x[Car-43]
	_ = x[Cdr-44]
	_ = x[Cons-45]
	_ = x[Dissoc-46]
	_ = x[Empty-47]
	_ = x[Get-48]
	_ = x[Nth-49]
	_ = x[Vector-50]
	_ = x[Eq-51]
	_ = x[Not-52]
	_ = x[Add-53]
	_ = x[Div-54]
	_ = x[Mod-55]
	_ = x[Mul-56]
	_ = x[Neg-57]
	_ = x[NegInt-58]
	_ = x[NumEq-59]
	_ = x[NumGt-60]
	_ = x[NumGte-61]
	_ = x[NumLt-62]
	_ = x[NumLte-63]
	_ = x[PosInt-64]
	_ = x[Sub-65]
}

const (
	_Opcode_name_0 = "LabelNoOpArgArgsLenArgsPopArgsPushArgsRestClosureEnvBindEnvPrivateEnvPublicEnvValueLoadNewRefRefBindRefValueStoreDupPopConstFalseNullTrueZeroCallCall0Call1Call2Call3CallSelfCallWithTailCallTailClosTailSelfCondJumpJumpPanicRetFalseRetNullRetTrueReturnAppendAssocCarCdrConsDissocEmptyGetNthVectorEqNotAddDivModMulNegNegIntNumEqNumGtNumGteNumLtNumLtePosIntSub"
	_Opcode_name_1 = "OpcodeMask"
)

var (
	_Opcode_index_0 = [...]uint16{0, 5, 9, 12, 19, 26, 34, 42, 49, 56, 66, 75, 83, 87, 93, 100, 108, 113, 116, 119, 124, 129, 133, 137, 141, 145, 150, 155, 160, 165, 173, 181, 189, 197, 205, 213, 217, 222, 230, 237, 244, 250, 256, 261, 264, 267, 271, 277, 282, 285, 288, 294, 296, 299, 302, 305, 308, 311, 314, 320, 325, 330, 336, 341, 347, 353, 356}
)

func (i Opcode) String() string {
	switch {
	case i <= 65:
		return _Opcode_name_0[_Opcode_index_0[i]:_Opcode_index_0[i+1]]
	case i == 127:
		return _Opcode_name_1
	default:
		return "Opcode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
