// Code generated by "stringer -output token_string.go -type TokenType"; DO NOT EDIT.

package read

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Error-0]
	_ = x[Identifier-1]
	_ = x[Dot-2]
	_ = x[String-3]
	_ = x[Number-4]
	_ = x[ListStart-5]
	_ = x[ListEnd-6]
	_ = x[VectorStart-7]
	_ = x[VectorEnd-8]
	_ = x[ObjectStart-9]
	_ = x[ObjectEnd-10]
	_ = x[QuoteMarker-11]
	_ = x[SyntaxMarker-12]
	_ = x[UnquoteMarker-13]
	_ = x[SpliceMarker-14]
	_ = x[PatternMarker-15]
	_ = x[Whitespace-16]
	_ = x[NewLine-17]
	_ = x[Comment-18]
	_ = x[endOfFile-19]
}

const _TokenType_name = "ErrorIdentifierDotStringNumberListStartListEndVectorStartVectorEndObjectStartObjectEndQuoteMarkerSyntaxMarkerUnquoteMarkerSpliceMarkerPatternMarkerWhitespaceNewLineCommentendOfFile"

var _TokenType_index = [...]uint8{0, 5, 15, 18, 24, 30, 39, 46, 57, 66, 77, 86, 97, 109, 122, 134, 147, 157, 164, 171, 180}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
