// Code generated by "stringer -output function_string.go -type Convention -linecomment"; DO NOT EDIT.

package api

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ApplicativeCall-0]
	_ = x[NormalCall-1]
	_ = x[MacroCall-2]
}

const _Convention_name = "ApplicativeNormalMacro"

var _Convention_index = [...]uint8{0, 11, 17, 22}

func (i Convention) String() string {
	if i < 0 || i >= Convention(len(_Convention_index)-1) {
		return "Convention(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Convention_name[_Convention_index[i]:_Convention_index[i+1]]
}
